const PROTECTED_ENTITY_TYPES = new Set([
  "evidence",
  "learning_goal",
  "mastery",
  "note",
  "note_document_state",
  "note_document_update",
  "quiz_attempt",
  "quiz_item",
  "resource",
  "error_pattern",
  "exam",
  "exam_subject",
  "syllabus_node",
  "mock_exam",
  "score_record",
  "learning_track",
  "study_project",
  "inbox_item",
  "deliverable",
  "paper_record",
  "research_claim",
  "research_question",
  "experiment_run",
  "metric_record",
  "research_feedback",
  "rubric",
  "group_review",
  "group_feedback",
  "report_snapshot",
  "audit_review",
  "review_finding",
  "review_schedule",
  "study_session",
  "task",
  "topic",
  "topic_dependency",
  "verification",
]);

export function isProtectedEntityType(entityType: string): boolean {
  return PROTECTED_ENTITY_TYPES.has(entityType);
}
