"""Read-only Zotero sync

Revision ID: 0047_zotero_sync
Revises: 0046_integration_credentials
Create Date: 2026-09-28 12:57:33.494490
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0047_zotero_sync"
down_revision: str | None = "0046_integration_credentials"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zotero_sync_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("library_id", sa.String(length=80), nullable=True),
        sa.Column("library_version", sa.BigInteger(), nullable=False),
        sa.Column("target_version", sa.BigInteger(), nullable=True),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("page_offset", sa.BigInteger(), nullable=False),
        sa.Column(
            "collections",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "item_map",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "jsonb_typeof(collections) = 'object' AND jsonb_typeof(item_map) = 'object'",
            name="ck_zotero_sync_maps",
        ),
        sa.CheckConstraint(
            "phase IN ('collections','items','attachments','annotations','deleted')",
            name="ck_zotero_sync_phase",
        ),
        sa.CheckConstraint(
            "library_version >= 0 AND page_offset >= 0 "
            "AND (target_version IS NULL OR target_version >= 0)",
            name="ck_zotero_sync_versions",
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"], ["integration_credentials.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["space_id", "workspace_id"],
            ["spaces.id", "spaces.workspace_id"],
            name="fk_zotero_sync_space",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "space_id", name="uq_zotero_sync_target"),
    )
    op.create_index("ix_zotero_sync_due", "zotero_sync_states", ["due_at"], unique=False)
    op.add_column(
        "integration_credentials",
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "resources",
        sa.Column(
            "zotero_sync_stopped", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "resources",
        sa.Column(
            "zotero_collection_keys",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "source_excerpts",
        sa.Column("origin", sa.String(length=16), server_default="logion", nullable=False),
    )
    op.add_column(
        "source_excerpts", sa.Column("zotero_annotation_key", sa.String(length=80), nullable=True)
    )
    op.add_column(
        "source_excerpts", sa.Column("zotero_annotation_version", sa.BigInteger(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_excerpt_zotero_edition",
        "source_excerpts",
        ["resource_id", "zotero_annotation_key", "zotero_annotation_version"],
    )
    op.create_check_constraint(
        "ck_resources_zotero_collections",
        "resources",
        "jsonb_typeof(zotero_collection_keys) = 'array'",
    )
    op.create_check_constraint(
        "ck_excerpt_origin",
        "source_excerpts",
        "(origin = 'logion' AND zotero_annotation_key IS NULL "
        "AND zotero_annotation_version IS NULL) OR "
        "(origin = 'zotero' AND zotero_annotation_key IS NOT NULL "
        "AND zotero_annotation_version IS NOT NULL AND zotero_annotation_version >= 0)",
    )


def downgrade() -> None:
    if op.get_bind().scalar(
        sa.text("""
        SELECT EXISTS (SELECT 1 FROM zotero_sync_states)
        OR EXISTS (SELECT 1 FROM source_excerpts WHERE origin <> 'logion')
        OR EXISTS (SELECT 1 FROM resources
                   WHERE zotero_sync_stopped OR zotero_collection_keys <> '[]'::jsonb)
        OR EXISTS (SELECT 1 FROM integration_credentials WHERE retry_after IS NOT NULL)
    """)
    ):
        raise RuntimeError("Preserve Zotero synchronization data before downgrade.")
    op.drop_constraint("ck_excerpt_origin", "source_excerpts", type_="check")
    op.drop_constraint("ck_resources_zotero_collections", "resources", type_="check")
    op.drop_constraint("uq_excerpt_zotero_edition", "source_excerpts", type_="unique")
    op.drop_column("source_excerpts", "zotero_annotation_version")
    op.drop_column("source_excerpts", "zotero_annotation_key")
    op.drop_column("source_excerpts", "origin")
    op.drop_column("resources", "zotero_collection_keys")
    op.drop_column("resources", "zotero_sync_stopped")
    op.drop_column("integration_credentials", "retry_after")
    op.drop_index("ix_zotero_sync_due", table_name="zotero_sync_states")
    op.drop_table("zotero_sync_states")
    # ### end Alembic commands ###
